DROP TABLE IF EXISTS Users, Courses, Enrollments;

CREATE TABLE Users (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    Username VARCHAR(100) NOT NULL,
    Password VARCHAR(255) NOT NULL,  -- Assuming the password might be hashed
    Role BOOLEAN NOT NULL  -- Assuming boolean values, use TINYINT if necessary
);

CREATE TABLE Courses (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    InstructorId INT NOT NULL,
    CourseCode VARCHAR(50) NOT NULL,
    Units INT NOT NULL,
    Capacity INT NOT NULL
);

CREATE TABLE Enrollments (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    StudentId INT NOT NULL,
    CourseId INT NOT NULL,
    CourseCode VARCHAR(100) NOT NULL,
    Grade VARCHAR(10) NOT NULL,
    FOREIGN KEY (CourseId) REFERENCES Courses(Id) ON DELETE CASCADE
);

INSERT INTO Users (Username, Password, Role) VALUES
('Dominic Sia', 'password', 0),
('Niyaniya', 'password', 1),
('Roger Uy', 'password', 1),
('Austin Fernandez', 'password', 1),
('Anish Shrestha', 'password', 1),
('Jonathan Cempron', 'password', 1),
('Thomas Tiam Lee', 'password', 1),
('Raphael Tan Ai', 'password', 0),
('Tean Concio', 'password', 0),
('Rafael Gamboer', 'password', 0),
('Marco You', 'password', 0),
('Jean Cabrera', 'password', 0),
('Nicole Ong', 'password', 0),
('Jaycee Montenegro', 'password', 0),
('Hannah Teves', 'password', 0),
('Alyanna Cabrera', 'password', 0),
('Chuanfa Wu', 'password', 0),
('Shaun Lim', 'password', 0),
('Bentley Lu', 'password', 0),
('Doron', 'password', 0),
('Jeremy Wang', 'password', 0),
('Orrin Uy', 'password', 0),
('Sealtiel Dy', 'password', 0),
('Djerwnapekhaper Saciut Hatshepsut', 'password', 0),
('Iroha Tamaki', 'password', 0),
('Takanashi Hoshino', 'password', 0),
('Lily', 'password', 0),
('Ibaraki Douji', 'password', 0),
('Super Galaxy Cosmo', 'password', 0),
('Christian Castillo', 'password', 0),
('Bruce Mercado', 'password', 0),
('Marisa Kirisame', 'password', 0),
('Patchouli Knowledge', 'password', 0),
('Alice Margatroid', 'password', 0),
('Supreme Calamitas', 'password', 0),
('Poppy', 'password', 0),
('Charlotta Fenia', 'password', 0),
('Chicken Jockey', 'password', 0),
('Sans Undertale', 'password', 0),
('Just Monika', 'password', 0),
('Am I actually supposed to think of this much names?', 'password', 0),
('Mika Misono', 'password', 0),
('Seia Yurizono', 'password', 0),
('Nagisa Kirifuji', 'password', 0),
('Yuzu Hanaoka', 'password', 0),
('Midori Saiba', 'password', 0),
('Momoi Saiba', 'password', 0),
('Arisu Tendou', 'password', 0),
('Shiroko Sunaookami', 'password', 0),
('Ayane Okusora', 'password', 0),
('Serika Kuromi', 'password', 0),
('Nonomi Izayoi', 'password', 0);

INSERT INTO Courses (InstructorId, CourseCode, Units, Capacity) VALUES
(2, 'GE-CRCTN', 3, 40),
(7, 'ST-INTSY', 3, 40),
(4, 'CS-OPESY', 3, 40),
(3, 'CS-ARCH1', 3, 25),
(5, 'CS-ALGCM', 3, 40),
(5, 'CC-DDSALG', 3, 40),
(6, 'CC-PROG3', 3, 40),
(4, 'ST-ALGCM', 3, 25);

INSERT INTO Enrollments (StudentId, CourseId, CourseCode, Grade) VALUES
(1, 1, 'GE-CRCTN', '3.0'),
(1, 2, 'ST-INTSY', '2.5'),
(6, 1, 'GE-CRCTN', '0.0'),
(6, 4, 'CS-ARCH1', '1.0'),
(7, 4, 'CS-ARCH1', '1.0'),
(8, 4, 'CS-ARCH1', '1.0'),
(9, 4, 'CS-ARCH1', '1.0'),
(10, 4, 'CS-ARCH1', '1.0'),
(11, 4, 'CS-ARCH1', '1.0'),
(12, 4, 'CS-ARCH1', '1.0'),
(13, 4, 'CS-ARCH1', '1.0'),
(14, 4, 'CS-ARCH1', '1.0'),
(15, 4, 'CS-ARCH1', '1.0'),
(16, 4, 'CS-ARCH1', '1.0'),
(17, 4, 'CS-ARCH1', '1.0'),
(18, 4, 'CS-ARCH1', '1.0'),
(19, 4, 'CS-ARCH1', '1.0'),
(20, 4, 'CS-ARCH1', '1.0'),
(21, 4, 'CS-ARCH1', '1.0'),
(22, 4, 'CS-ARCH1', '1.0'),
(23, 4, 'CS-ARCH1', '1.0'),
(24, 4, 'CS-ARCH1', '1.0'),
(25, 4, 'CS-ARCH1', '1.0'),
(26, 4, 'CS-ARCH1', '1.0'),
(27, 4, 'CS-ARCH1', '1.0'),
(28, 4, 'CS-ARCH1', '1.0'),
(29, 4, 'CS-ARCH1', '1.0'),
(30, 4, 'CS-ARCH1', '1.0'),
(31, 5, 'CS-ALGCM', '1.0'),
(33, 8, 'ST-ALGCM', '1.0'),
(34, 8, 'ST-ALGCM', '1.0'),
(35, 8, 'ST-ALGCM', '1.0'),
(36, 8, 'ST-ALGCM', '1.0'),
(37, 8, 'ST-ALGCM', '1.0'),
(37, 1, 'GE-CRCTN', '1.0'),
(38, 8, 'ST-ALGCM', '1.0'),
(39, 8, 'ST-ALGCM', '1.0'),
(40, 8, 'ST-ALGCM', '1.0'),
(42, 8, 'ST-ALGCM', '1.0'),
(41, 8, 'ST-ALGCM', '1.0'),
(43, 8, 'ST-ALGCM', '1.0'),
(44, 8, 'ST-ALGCM', '1.0'),
(45, 8, 'ST-ALGCM', '1.0'),
(46, 8, 'ST-ALGCM', '1.0'),
(47, 8, 'ST-ALGCM', '1.0'),
(48, 8, 'ST-ALGCM', '1.0'),
(49, 8, 'ST-ALGCM', '1.0'),
(6, 8, 'ST-ALGCM', '1.0'),
(1, 8, 'ST-ALGCM', '1.0'),
(7, 1, 'GE-CRCTN', '1.0'),
(50, 5, 'CC-DDSALG', '1.0'),
(51, 5, 'CC-DDSALG', '1.0'),
(52, 5, 'CC-DDSALG', '1.0'),
(13, 5, 'CC-DDSALG', '1.0'),
(14, 5, 'CC-DDSALG', '1.0'),
(15, 5, 'CC-DDSALG', '1.0'),
(32, 5, 'CC-DDSALG', '1.0'),
(7, 5, 'CC-DDSALG', '1.0'),
(8, 5, 'CC-DDSALG', '1.0');